"""Load canonical non-spatial model settings from the registry TOML."""

from __future__ import annotations

from copy import deepcopy
from dataclasses import dataclass
from pathlib import Path
import re
import tomllib

from ._toml import require_bool, require_int, require_number, require_table


SUPPORTED_STORAGE_REQUIREMENTS = {
    "none",
    "minimum_cumulative_activity",
}
SUPPORTED_EMISSIONS_PROJECTION_METHODS = {"constant"}
SUPPORTED_BASEMAP_GRID_TYPES = {"geographic", "projected"}
MODEL_SECTIONS = {
    "time",
    "finance",
    "emissions",
    "storage",
    "legacy_gasoline",
    "basemap",
}
SCENARIO_ID_PATTERN = re.compile(
    r"^[a-z0-9](?:[a-z0-9-]{0,18}[a-z0-9])?$"
)


@dataclass(frozen=True)
class ModelTimeConfig:
    """Single optimization-period horizon defined by start and end years."""

    start_year: int
    end_year: int

    @property
    def period_years(self) -> int:
        """Return the duration of the single optimization period."""

        return self.end_year - self.start_year


@dataclass(frozen=True)
class ModelFinanceConfig:
    """Discounting and default financing assumptions."""

    global_discount_rate: float
    default_loan_rate: float


@dataclass(frozen=True)
class ModelEmissionsConfig:
    """Projection used to represent annual Silver emissions in Gold."""

    projection_method: str


@dataclass(frozen=True)
class ModelStorageConfig:
    """Policy requirement for cumulative geological CO2 injection."""

    requirement: str
    minimum_cumulative_activity: float


@dataclass(frozen=True)
class ModelLegacyGasolineConfig:
    """Optional node-level existing ("legacy") gasoline supply assumption.

    Represents gasoline already available at a demand node (e.g. already in
    the tank at the point of sale), fully decoupled from the CO2-capture /
    e-fuel synthesis chain (``CO2_CAP -> METOH_PLANT -> GSL_PLANT``). Disabled
    by default.
    """

    enabled: bool
    years_of_demand: float


@dataclass(frozen=True)
class ModelBasemapConfig:
    """Resolution selected from the Silver basemaps generated by a build profile.

    Attributes
    ----------
    grid_type : str
        Basemap grid family to select from: ``"geographic"`` (EPSG:4326,
        decimal degrees) or ``"projected"`` (EPSG:3347, kilometres).
    resolution : float
        Resolution value, in the selected grid family's native unit, that must
        exactly match a resolution actually generated for the active build
        profile's Silver basemaps.
    """

    grid_type: str
    resolution: float


@dataclass(frozen=True)
class ModelScenarioConfig:
    """Identity and source of one scenario applied over global defaults."""

    scenario_id: str
    description: str
    source_path: Path | None


@dataclass(frozen=True)
class ModelConfig:
    """Validated canonical model settings loaded from ``registry/model.toml``."""

    time: ModelTimeConfig
    finance: ModelFinanceConfig
    emissions: ModelEmissionsConfig
    storage: ModelStorageConfig
    legacy_gasoline: ModelLegacyGasolineConfig
    basemap: ModelBasemapConfig
    scenario: ModelScenarioConfig
    source_path: Path


def _require_rate(table: dict, key: str, section: str) -> float:
    value = require_number(table, key, section)
    if not 0 <= value < 1:
        raise ValueError(f"[{section}].{key} must satisfy 0 <= rate < 1.")
    return value


def _require_nonnegative_number(table: dict, key: str, section: str) -> float:
    value = require_number(table, key, section)
    if value < 0:
        raise ValueError(f"[{section}].{key} must be nonnegative.")
    return value


def _require_positive_number(table: dict, key: str, section: str) -> float:
    value = require_number(table, key, section)
    if value <= 0:
        raise ValueError(f"[{section}].{key} must be greater than 0.")
    return value


def _apply_scenario_overrides(
    base: dict,
    scenario_path: Path,
) -> tuple[dict, ModelScenarioConfig]:
    """Overlay validated scenario fields onto global model defaults."""

    if not scenario_path.is_file():
        raise FileNotFoundError(f"Model scenario not found: {scenario_path}")

    with scenario_path.open("rb") as scenario_file:
        scenario_raw = tomllib.load(scenario_file)

    unknown_sections = set(scenario_raw) - (MODEL_SECTIONS | {"scenario"})
    if unknown_sections:
        raise ValueError(
            "Scenario contains unsupported sections: "
            f"{sorted(unknown_sections)}."
        )

    identity = require_table(scenario_raw, "scenario")
    unknown_identity_keys = set(identity) - {"id", "description"}
    if unknown_identity_keys:
        raise ValueError(
            "[scenario] contains unsupported settings: "
            f"{sorted(unknown_identity_keys)}."
        )

    scenario_id = identity.get("id")
    if not isinstance(scenario_id, str) or not SCENARIO_ID_PATTERN.fullmatch(
        scenario_id
    ):
        raise ValueError(
            "[scenario].id must contain 1-20 lowercase letters, numbers, or "
            "hyphens, and must start and end with a letter or number."
        )
    description = identity.get("description", "")
    if not isinstance(description, str):
        raise ValueError("[scenario].description must be a string.")

    effective = deepcopy(base)
    for section in MODEL_SECTIONS:
        if section not in scenario_raw:
            continue
        overrides = scenario_raw[section]
        if not isinstance(overrides, dict):
            raise ValueError(f"Scenario section [{section}] must be a table.")
        unknown_keys = set(overrides) - set(require_table(base, section))
        if unknown_keys:
            raise ValueError(
                f"Scenario [{section}] contains unsupported settings: "
                f"{sorted(unknown_keys)}."
            )
        effective[section].update(overrides)

    return effective, ModelScenarioConfig(
        scenario_id=scenario_id,
        description=description.strip(),
        source_path=scenario_path,
    )


def load_model_config(
    config_path: Path | str,
    scenario_path: Path | str | None = None,
) -> ModelConfig:
    """Load global model defaults and apply an optional scenario overlay."""

    config_path = Path(config_path).expanduser().resolve()
    if not config_path.is_file():
        raise FileNotFoundError(f"Model registry configuration not found: {config_path}")

    with config_path.open("rb") as config_file:
        raw = tomllib.load(config_file)

    if scenario_path is None:
        scenario = ModelScenarioConfig(
            scenario_id="defaults",
            description="Global model defaults without a scenario overlay",
            source_path=None,
        )
    else:
        resolved_scenario_path = Path(scenario_path).expanduser().resolve()
        raw, scenario = _apply_scenario_overrides(
            raw,
            resolved_scenario_path,
        )

    time_raw = require_table(raw, "time")
    finance_raw = require_table(raw, "finance")
    emissions_raw = require_table(raw, "emissions")
    storage_raw = require_table(raw, "storage")
    basemap_raw = require_table(raw, "basemap")

    start_year = require_int(time_raw, "start_year", "time")
    end_year = require_int(time_raw, "end_year", "time")
    if end_year <= start_year:
        raise ValueError("[time].end_year must be greater than [time].start_year.")

    projection_method = emissions_raw.get("projection_method")
    if projection_method not in SUPPORTED_EMISSIONS_PROJECTION_METHODS:
        raise ValueError(
            "[emissions].projection_method must be one of "
            f"{sorted(SUPPORTED_EMISSIONS_PROJECTION_METHODS)}."
        )

    requirement = storage_raw.get("requirement")
    if requirement not in SUPPORTED_STORAGE_REQUIREMENTS:
        raise ValueError(
            "[storage].requirement must be one of "
            f"{sorted(SUPPORTED_STORAGE_REQUIREMENTS)}."
        )
    minimum_cumulative_activity = _require_nonnegative_number(
        storage_raw,
        "minimum_cumulative_activity",
        "storage",
    )
    if requirement == "none" and minimum_cumulative_activity != 0:
        raise ValueError(
            "[storage].minimum_cumulative_activity must be 0 when the requirement "
            "is 'none'."
        )
    if (
        requirement == "minimum_cumulative_activity"
        and minimum_cumulative_activity <= 0
    ):
        raise ValueError(
            "[storage].minimum_cumulative_activity must be greater than 0 when "
            "the requirement is 'minimum_cumulative_activity'."
        )

    legacy_gasoline_raw = require_table(raw, "legacy_gasoline")
    legacy_gasoline_enabled = require_bool(
        legacy_gasoline_raw,
        "enabled",
        "legacy_gasoline",
    )
    legacy_gasoline_years_of_demand = _require_nonnegative_number(
        legacy_gasoline_raw,
        "years_of_demand",
        "legacy_gasoline",
    )
    if not legacy_gasoline_enabled and legacy_gasoline_years_of_demand != 0:
        raise ValueError(
            "[legacy_gasoline].years_of_demand must be 0 when enabled is "
            "false."
        )
    if legacy_gasoline_enabled and legacy_gasoline_years_of_demand <= 0:
        raise ValueError(
            "[legacy_gasoline].years_of_demand must be greater than 0 when "
            "enabled is true."
        )

    basemap_grid_type = basemap_raw.get("grid_type")
    if basemap_grid_type not in SUPPORTED_BASEMAP_GRID_TYPES:
        raise ValueError(
            "[basemap].grid_type must be one of "
            f"{sorted(SUPPORTED_BASEMAP_GRID_TYPES)}."
        )
    basemap_resolution = _require_positive_number(
        basemap_raw,
        "resolution",
        "basemap",
    )

    return ModelConfig(
        time=ModelTimeConfig(start_year=start_year, end_year=end_year),
        finance=ModelFinanceConfig(
            global_discount_rate=_require_rate(
                finance_raw,
                "global_discount_rate",
                "finance",
            ),
            default_loan_rate=_require_rate(
                finance_raw,
                "default_loan_rate",
                "finance",
            ),
        ),
        emissions=ModelEmissionsConfig(
            projection_method=projection_method,
        ),
        storage=ModelStorageConfig(
            requirement=requirement,
            minimum_cumulative_activity=minimum_cumulative_activity,
        ),
        legacy_gasoline=ModelLegacyGasolineConfig(
            enabled=legacy_gasoline_enabled,
            years_of_demand=legacy_gasoline_years_of_demand,
        ),
        basemap=ModelBasemapConfig(
            grid_type=basemap_grid_type,
            resolution=basemap_resolution,
        ),
        scenario=scenario,
        source_path=config_path,
    )
